# schema_config.yaml
tables:
  sales:
    description: "Contains all sales transactions with details about products, customers, and revenue"
    create_statement: >
      CREATE TABLE sales (
        sale_id INT,
        date DATE,
        product_id INT,
        customer_id INT,
        quantity INT,
        revenue FLOAT,
        discount FLOAT,
        FOREIGN KEY (product_id) REFERENCES products(product_id),
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
      )
    columns:
      - name: sale_id
        type: INT
        description: "Unique identifier for each sale transaction"
      - name: date
        type: DATE
        description: "Date when the sale occurred"
      - name: product_id
        type: INT
        description: "Reference to the product that was sold"
      - name: customer_id
        type: INT
        description: "Reference to the customer who made the purchase"
      - name: quantity
        type: INT
        description: "Number of units sold in this transaction"
      - name: revenue
        type: FLOAT
        description: "Total revenue generated from this sale"
      - name: discount
        type: FLOAT
        description: "Discount amount applied to this sale"

  products:
    description: "Master table containing all product information including categories and pricing"
    create_statement: >
      CREATE TABLE products (
        product_id INT PRIMARY KEY,
        name VARCHAR(100),
        category VARCHAR(50),
        subcategory VARCHAR(50),
        base_price FLOAT,
        current_stock INT
      )
    columns:
      - name: product_id
        type: INT
        description: "Unique identifier for each product"
      - name: name
        type: VARCHAR
        description: "Name of the product"
      - name: category
        type: VARCHAR
        description: "Main category of the product"
      - name: subcategory
        type: VARCHAR
        description: "Subcategory for more detailed classification"
      - name: base_price
        type: FLOAT
        description: "Standard price before any discounts"
      - name: current_stock
        type: INT
        description: "Current inventory level"

  customers:
    description: "Customer master data including demographic and location information"
    create_statement: >
      CREATE TABLE customers (
        customer_id INT PRIMARY KEY,
        name VARCHAR(100),
        region VARCHAR(50),
        segment VARCHAR(50),
        registration_date DATE,
        lifetime_value FLOAT
      )
    columns:
      - name: customer_id
        type: INT
        description: "Unique identifier for each customer"
      - name: name
        type: VARCHAR
        description: "Customer's full name"
      - name: region
        type: VARCHAR
        description: "Geographical region of the customer"
      - name: segment
        type: VARCHAR
        description: "Customer segment (e.g., Premium, Regular)"
      - name: registration_date
        type: DATE
        description: "Date when customer first registered"
      - name: lifetime_value
        type: FLOAT
        description: "Total value of all purchases by this customer"

analysis_patterns:
  time_series:
    - "trend"
    - "over time"
    - "monthly"
    - "daily"
    - "growth"
  comparison:
    - "compare"
    - "difference"
    - "versus"
    - "vs"
  distribution:
    - "distribution"
    - "spread"
    - "range"
  composition:
    - "breakdown"
    - "percentage"
    - "ratio"
    - "share"
